# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

# Gitleaks configuration
# https://github.com/gitleaks/gitleaks

title = "Gitleaks config for eudiw-wallet-token-lib"

[allowlist]
  description = "Allowlisted paths"
  paths = [
    '''src/test/.*''',
    '''.*test.*'''
  ]
